Repository dnd-side-project/dnd-9th-2-ios, pull requests merged in 2023-09, with the labels that each got.

#236 모임 수정 View & 방장 넘기기 & 방 폭파하기
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/Common/Extensions/Date/Date+.swift
  Baggle/Baggle/Core/Models/Alert/MeetingDetail/AlertMeetingDetailType.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/MeetingDetail.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/Memeber.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingEdit/MeetingEdit.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingLeave/MeetingLeaveMember.swift
  Baggle/Baggle/Core/Models/Network/MeetingDetail/MeetingDetailEntity.swift
  Baggle/Baggle/DesignSystem/View/Text/TextEditor/BaggleTextEditor.swift
  Baggle/Baggle/DesignSystem/View/Text/TextField/BaggleTextField.swift
  Baggle/Baggle/Features/Common/MeetingDateButton/MeetingDateButton.swift
  Baggle/Baggle/Features/Common/MeetingDateButton/MeetingDateButtonFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingEdit/MeetingEditFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingEdit/MeetingEditView.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/MeetingLeaveMemberView.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/MemberInfoView.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/SelectOwnerFeature.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/SelectOwnerView.swift
  Baggle/Baggle/Features/Tab/CreateMeeting/Date/CreateDateFeature.swift
  Baggle/Baggle/Features/Tab/CreateMeeting/Date/CreateDateView.swift
  Baggle/Baggle/Features/Tab/CreateMeeting/Title/CreateTitleFeature.swift
  Baggle/Baggle/Features/Tab/Home/Common/CircleProfileView.swift
  Baggle/Baggle/Features/Tab/Home/HomeFeature.swift
  Baggle/Baggle/Features/Tab/Home/HomeView.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabFeature.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabView.swift
  Baggle/Baggle/Features/Tab/MyPage/MyPageView.swift
Labels: feat, fix

#237 Feature - 모임 상세 custom actionsheet 구현
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/Common/Foundation/NotificationCenter/Notification+Name.swift
  Baggle/Baggle/DesignSystem/Extension/View+.swift
  Baggle/Baggle/DesignSystem/Extension/View+Modifier.swift
  Baggle/Baggle/DesignSystem/View/ActionSheet/BaggleActionSheet.swift
  Baggle/Baggle/DesignSystem/View/Button/BaggleButtonStyle.swift
  Baggle/Baggle/DesignSystem/View/Common/ShadeView.swift
  Baggle/Baggle/DesignSystem/View/Common/UnderlineView.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
Labels: feat

#242 Alert & Action Sheet 애니메이션 동작 수정
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/DesignSystem/Extension/View+.swift
  Baggle/Baggle/DesignSystem/View/ActionSheet/BaggleActionSheet.swift
  Baggle/Baggle/DesignSystem/View/Alert/BaggleAlert.swift
  Baggle/Baggle/DesignSystem/View/Alert/BaggleAlertOneButton.swift
  Baggle/Baggle/DesignSystem/View/Alert/BaggleAlertTwoButton.swift
  Baggle/Baggle/DesignSystem/View/Common/ShadeView.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
Labels: fix

#243 방장 위임하고 나가기
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/API/MemberAPI.swift
  Baggle/Baggle/Core/Models/Alert/Home/MeetingDetail/AlertMeetingDetailType.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingDelete/MeetingDeleteResult.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingDelete/MeetingDeleteService.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/SelectOwnerFeature.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/SelectOwnerView.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabFeature.swift
Labels: feat

#248 Fix - Service retrying 로직 수정
  Baggle/Baggle/Core/Common/Extensions/Foundation/Task+.swift
  Baggle/Baggle/Core/Models/Alert/Home/MeetingDetail/Emergency/AlertEmergencyType.swift
  Baggle/Baggle/Core/Services/Common/NetworkService.swift
  Baggle/Baggle/Core/Services/Emergency/EmergencyService.swift
  Baggle/Baggle/Core/Services/Error/APIError.swift
  Baggle/Baggle/Core/Services/Home/MeetingListService.swift
  Baggle/Baggle/Core/Services/JoinMeeting/JoinMeetingService.swift
  Baggle/Baggle/Core/Services/Login/LoginService.swift
  Baggle/Baggle/Core/Services/SignUp/SignUpService.swift
  Baggle/Baggle/Core/Services/Tab/LogoutService.swift
  Baggle/Baggle/Core/Services/Tab/WithdrawService.swift
  Baggle/Baggle/Features/App/AppFeature.swift
  Baggle/Baggle/Features/MeetingDetail/Emergency/EmergencyFeature.swift
Labels: fix

#249 방장이 모임 폭파 & 모임 떠나기 & Action Sheet 분기 처리
  Baggle/Baggle/Core/API/MeetingAPI.swift
  Baggle/Baggle/Core/API/MemberAPI.swift
  Baggle/Baggle/Core/Models/Alert/Home/MeetingDetail/AlertMeetingDetailType.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/MeetingDetail.swift
  Baggle/Baggle/Core/Models/Network/MeetingDetail/MeetingDetailEntity.swift
  Baggle/Baggle/Core/Services/Common/NetworkService.swift
  Baggle/Baggle/Core/Services/Error/APIError.swift
  Baggle/Baggle/Core/Services/Login/LoginService.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingDelete/MeetingDeleteResult.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingDelete/MeetingDeleteService.swift
  Baggle/Baggle/DesignSystem/View/Alert/BaggleAlert.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
Labels: feat, fix

#251 Fix - 로그아웃 후 재로그인시 유저 정보 에러 뜨는 문제 해결
  Baggle/Baggle/Core/Models/Alert/Tab/AlertMainTabType.swift
  Baggle/Baggle/Features/App/AppFeature.swift
  Baggle/Baggle/Features/Tab/Home/HomeFeature.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabView.swift
Labels: fix

#252 Feat #231 - License Plist 오픈소스 라이브러리 연결
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Settings.bundle/Root.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Baggle/Settings.bundle/com.mono0926.LicensePlist.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/Alamofire.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/GoogleAppMeasurement.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/GoogleDataTransport.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/GoogleUtilities.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/Kingfisher.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/Moya.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/ReactiveSwift.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/RxSwift.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/abseil-cpp-binary.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/combine-schedulers.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/firebase-ios-sdk.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/grpc-binary.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/gtm-session-fetcher.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/kakao-ios-sdk.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/leveldb.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/lottie-spm.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/nanopb.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/promises.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-case-paths.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-clocks.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-collections.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-composable-architecture.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-concurrency-extras.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-custom-dump.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-dependencies.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-identified-collections.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swift-protobuf.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/swiftui-navigation.plist
  Baggle/Settings.bundle/com.mono0926.LicensePlist/xctest-dynamic-overlay.plist
  Baggle/Settings.bundle/en.lproj/Root.strings
Labels: feat

#254 Fix #253 - jwt reissue api request body 수정
  Baggle/Baggle/Core/API/UserAPI.swift
  Baggle/Baggle/Core/Services/Common/TokenRefreshService.swift
Labels: fix

#255 Fix - 모임 상세 인증 후 다른 참여자 탈락으로 뜨는 문제 해결
  Baggle/Baggle/Core/API/MeetingAPI.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/MeetingDetail.swift
  Baggle/Baggle/Core/Models/Network/Feed/FeedPhotoEntity.swift
  Baggle/Baggle/Core/Models/Network/MeetingStatus/MeetingStatusEntity.swift
  Baggle/Baggle/Core/Services/Camera/Camera.swift
  Baggle/Baggle/Features/App/AppFeature.swift
  Baggle/Baggle/Features/Camera/CameraView.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/MeetingLeaveMemberView.swift
  Baggle/Baggle/Features/MeetingDetail/SelectHost/SelectOwnerView.swift
  Baggle/Baggle/Features/Tab/CreateMeeting/Date/CreateDateFeature.swift
  Baggle/Baggle/Features/Tab/CreateMeeting/Title/CreateTitleView.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabFeature.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabView.swift
Labels: fix

#256 모임 수정 API 연결
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/API/MeetingAPI.swift
  Baggle/Baggle/Core/Common/Extensions/Date/Date+.swift
  Baggle/Baggle/Core/Models/Alert/Home/MeetingDetail/AlertMeetingDetailType.swift
  Baggle/Baggle/Core/Models/Alert/Home/MeetingDetail/MeetingEdit/AlertMeetingEditType.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/MeetingDetail.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingEdit/MeetingEditModel.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingEdit/MeetingEditSuccessModel.swift
  Baggle/Baggle/Core/Models/Meeting/Status/MeetingEmergencyStatus.swift
  Baggle/Baggle/Core/Models/Network/MeetingEdit/MeetingEditEntity.swift
  Baggle/Baggle/Core/Models/Network/MeetingEdit/MeetingEditRequestModel.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingDetail/MeetingDetailService.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingEdit/MeetingEditResult.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingEdit/MeetingEditService.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingEdit/MeetingEditFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingEdit/MeetingEditView.swift
  Baggle/Baggle/Features/Tab/CreateMeeting/Date/CreateDateFeature.swift
  Baggle/Baggle/Features/Tab/MainTab/MainTabFeature.swift
Labels: feat

#258 README.md 업데이트
  README.md
Labels: documentation

#261 Fix - 홈 에러, 로딩 뷰 수정
  Baggle/Baggle/DesignSystem/Extension/Image+.swift
  Baggle/Baggle/Features/Tab/Home/Common/HomeStatus.swift
  Baggle/Baggle/Features/Tab/Home/HomeView.swift
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_error.imageset/Contents.json
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_error.imageset/img_error.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_error.imageset/img_error@2x.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_error.imageset/img_error@3x.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_loading.imageset/Contents.json
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_loading.imageset/img_loading.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_loading.imageset/img_loading@2x.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/Background/img_loading.imageset/img_loading@3x.png
Labels: fix

#262 Feature - 게시글 신고 뷰, API 연결 구현
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/API/BaseAPI.swift
  Baggle/Baggle/Core/API/ReportAPI.swift
  Baggle/Baggle/Core/Models/Feed/FeedReportRequestModel.swift
  Baggle/Baggle/Core/Services/Feed/FeedReportResult.swift
  Baggle/Baggle/Core/Services/Feed/FeedReportService.swift
  Baggle/Baggle/Core/Services/Meeting/MeetingDetail/MeetingDetailService.swift
  Baggle/Baggle/Features/MeetingDetail/FeedReport/FeedReportFeature.swift
  Baggle/Baggle/Features/MeetingDetail/FeedReport/FeedReportView.swift
  Baggle/Baggle/Features/MeetingDetail/FeedReport/ReportType.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
Labels: feat

#269 홈 에셋 변경, Const 파일 통합
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/Common/Const/Account.swift
  Baggle/Baggle/Core/Common/Const/Animation.swift
  Baggle/Baggle/Core/Common/Const/Const.swift
  Baggle/Baggle/Core/Common/Const/ErrorID.swift
  Baggle/Baggle/Core/Common/Const/Image.swift
  Baggle/Baggle/Core/Common/Const/URL.swift
  Baggle/Baggle/Features/Tab/Home/HomeView.swift
  Baggle/Baggle/Resources/Assets.xcassets/Images/BaggleText/MainHome.imageset/MainHome.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/BaggleText/MainHome.imageset/MainHome@2x.png
  Baggle/Baggle/Resources/Assets.xcassets/Images/BaggleText/MainHome.imageset/MainHome@3x.png
Labels: chore

#272 피드 신고 & 서버, 테스트 URL 분리 & 마이페이지 URL 수정
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/API/BaseAPI.swift
  Baggle/Baggle/Core/API/ReportAPI.swift
  Baggle/Baggle/Core/Common/Const/Const.swift
  Baggle/Baggle/Core/Models/Feed/Feed.swift
  Baggle/Baggle/Core/Models/Feed/FeedReportRequestModel.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/MeetingDetail.swift
  Baggle/Baggle/Core/Models/Meeting/MeetingDetail/Member.swift
  Baggle/Baggle/Core/Models/Network/Feed/FeedPhotoEntity.swift
  Baggle/Baggle/Core/Models/Network/MeetingDetail/MeetingDetailMemberEntity.swift
  Baggle/Baggle/Core/Services/Feed/FeedReportResult.swift
  Baggle/Baggle/Core/Services/Feed/FeedReportService.swift
  Baggle/Baggle/Features/Login/LoginFeature.swift
  Baggle/Baggle/Features/Login/LoginView.swift
  Baggle/Baggle/Features/MeetingDetail/Common/FeedListCell.swift
  Baggle/Baggle/Features/MeetingDetail/ImageDetail/ImageDetailView.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailFeature.swift
  Baggle/Baggle/Features/MeetingDetail/MeetingDetailView.swift
  Baggle/Baggle/Features/Tab/Home/HomeFeature.swift
  Baggle/Baggle/Info.plist
Labels: feat

#277 Hotfix - Date Format 수정
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/Common/Extensions/Date/Date+.swift
  Baggle/Baggle/DesignSystem/View/Date/Picker/BaggleDatePickerView.swift
  Baggle/Baggle/DesignSystem/View/Date/Picker/BaggleTimePickerView.swift
Labels: bug, fix

#278 앱 배포 1.0.0 (2)
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/Common/Extensions/Date/Date+.swift
  Baggle/Baggle/DesignSystem/View/Date/Picker/BaggleDatePickerView.swift
  Baggle/Baggle/DesignSystem/View/Date/Picker/BaggleTimePickerView.swift
Labels: bug

#280 Fix - Release, Develop config 파일 분리
  .github/workflows/build.yml
  Baggle/Baggle.xcodeproj/project.pbxproj
  Baggle/Baggle/Core/API/BaseAPI.swift
Labels: fix
